export const GET_POKEMONS = 'GET_POKEMONS';
export const CREATE_POKEMON = 'CREATE_POKEMON';
export const GET_TYPES = 'GET_TYPES';
export const GET_POKEMONS_FILTERED = 'GET_POKEMONS_FILTERED';
export const SORT_BY_TYPE = 'SORT_BY_TYPE';
export const SORT_BY_CREATED_BY = 'SORT_BY_CREATED_BY';
export const DELETE_POKEMON_STATE = 'DELETE_POKEMON_STATE';